export const LOAD_LUNCHES_SUCCESS = 'LOAD_LUNCHES_SUCCESS';
export const SHUFFLE_LUNCHES = 'SHUFFLE_LUNCHES';
export const DELETE_LUNCH = 'DELETE_LUNCH';
export const ADD_LUNCH = 'ADD_LUNCH';
export const ADD_MEAL = 'ADD_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';